version: '3.7'

volumes:
  api_mongo_volume:

services:
  mongo-datasource:
    image: mongo:7.0.6
    ports:
      - "27017:27017"
    volumes:
      - api_mongo_volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopwd


## Terminal cmd:
# docker container run --rm \
#    -e MONGO_INITDB_ROOT_USERNAME=mongouser \
#    -e MONGO_INITDB_ROOT_PASSWORD=mongopwd \
#    -v api_mongo_volume:/data/db \
#    -p 27017:27017 \
#    mongo